// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID             int32
	UserID         pgtype.Int4
	DocumentType   string
	DocumentNumber string
	FirstName      pgtype.Text
	LastName       pgtype.Text
	Sex            pgtype.Text
	BirthDate      pgtype.Date
	ExpireDate     pgtype.Date
	CountryCode    pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type EmailVerificationToken struct {
	ID        int32
	UserID    pgtype.Int4
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type Payment struct {
	ID            int32
	UserID        pgtype.Int4
	Amount        pgtype.Numeric
	CreditsAdded  int32
	PaymentDate   pgtype.Timestamp
	PaymentStatus string
}

type ScanningHistory struct {
	ID          int32
	UserID      pgtype.Int4
	DocumentID  pgtype.Int4
	DocumentUrl string
	ScanDate    pgtype.Timestamp
}

type User struct {
	ID              int32
	Email           string
	PasswordHash    string
	IsEmailVerified pgtype.Bool
	Credits         pgtype.Int4
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type UserSession struct {
	ID        int32
	UserID    pgtype.Int4
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
